name: Bandit Scan

on:
  push:
    branches:
      - main  # Adjust this to your main branch name
  pull_request:
    branches:
      - main  # Adjust this to your main branch name

jobs:
  bandit_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you want to use

    - name: Install dependencies
      run: pip install bandit

    - name: Run Bandit scan
      run: bandit -r .
